name: app_device_integrity
description: "This plugin was created to make your app attestation more easy. It uses the Native Attestation Providers from Apple and Google, App Attest and Play Integrity respectively, to generate tokens to be decrypted by your Server to check if your app is being accessed by a reliable device."
version: 1.0.0
homepage: https://bubotech.co

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: co.bubotech.app_device_integrity
        pluginClass: AppDeviceIntegrityPlugin
      ios:
        pluginClass: AppDeviceIntegrityPlugin